/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTIC_DIAGNOSTICS_PB_H_INCLUDED
#define PB_MESHTASTIC_DIAGNOSTICS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _meshtastic_LoDBDiagnosticsTest {
    uint32_t id;
    char value[64];
    uint32_t timestamp;
    bool active;
} meshtastic_LoDBDiagnosticsTest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define meshtastic_LoDBDiagnosticsTest_init_default {0, "", 0, 0}
#define meshtastic_LoDBDiagnosticsTest_init_zero {0, "", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define meshtastic_LoDBDiagnosticsTest_id_tag    1
#define meshtastic_LoDBDiagnosticsTest_value_tag 2
#define meshtastic_LoDBDiagnosticsTest_timestamp_tag 3
#define meshtastic_LoDBDiagnosticsTest_active_tag 4

/* Struct field encoding specification for nanopb */
#define meshtastic_LoDBDiagnosticsTest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         3) \
X(a, STATIC,   SINGULAR, BOOL,     active,            4)
#define meshtastic_LoDBDiagnosticsTest_CALLBACK NULL
#define meshtastic_LoDBDiagnosticsTest_DEFAULT NULL

extern const pb_msgdesc_t meshtastic_LoDBDiagnosticsTest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meshtastic_LoDBDiagnosticsTest_fields &meshtastic_LoDBDiagnosticsTest_msg

/* Maximum encoded size of messages (where known) */
#define MESHTASTIC_DIAGNOSTICS_PB_H_MAX_SIZE     meshtastic_LoDBDiagnosticsTest_size
#define meshtastic_LoDBDiagnosticsTest_size      79

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
