/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHTASTIC_EMERGENCY_PB_H_INCLUDED
#define PB_MESHTASTIC_EMERGENCY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _meshtastic_DeviceRole {
    meshtastic_DeviceRole_CLIENT = 0,
    meshtastic_DeviceRole_CLIENT_MUTE = 1,
    meshtastic_DeviceRole_ROUTER = 2,
    meshtastic_DeviceRole_ROUTER_CLIENT = 3,
    meshtastic_DeviceRole_REPEATER = 4,
    meshtastic_DeviceRole_TRACKER = 5,
    meshtastic_DeviceRole_SENSOR = 6,
    meshtastic_DeviceRole_TAK = 7,
    meshtastic_DeviceRole_CLIENT_HIDDEN = 8,
    meshtastic_DeviceRole_LOST_AND_FOUND = 9,
    meshtastic_DeviceRole_TAK_TRACKER = 10,
    meshtastic_DeviceRole_ROUTER_LATE = 11
} meshtastic_DeviceRole;

/* Struct definitions */
typedef struct _meshtastic_EmergencyConfig {
    bool emergency_mode_active;
    pb_callback_t whitelist_node_ids;
    pb_callback_t trigger_string;
    bool allow_public_text_messages;
    uint32_t lora_tx_power_override;
    float lora_freq_override;
    meshtastic_DeviceRole device_role;
    uint32_t position_broadcast_secs;
} meshtastic_EmergencyConfig;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _meshtastic_DeviceRole_MIN meshtastic_DeviceRole_CLIENT
#define _meshtastic_DeviceRole_MAX meshtastic_DeviceRole_ROUTER_LATE
#define _meshtastic_DeviceRole_ARRAYSIZE ((meshtastic_DeviceRole)(meshtastic_DeviceRole_ROUTER_LATE+1))

#define meshtastic_EmergencyConfig_device_role_ENUMTYPE meshtastic_DeviceRole


/* Initializer values for message structs */
#define meshtastic_EmergencyConfig_init_default  {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, _meshtastic_DeviceRole_MIN, 0}
#define meshtastic_EmergencyConfig_init_zero     {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, _meshtastic_DeviceRole_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define meshtastic_EmergencyConfig_emergency_mode_active_tag 1
#define meshtastic_EmergencyConfig_whitelist_node_ids_tag 2
#define meshtastic_EmergencyConfig_trigger_string_tag 3
#define meshtastic_EmergencyConfig_allow_public_text_messages_tag 4
#define meshtastic_EmergencyConfig_lora_tx_power_override_tag 5
#define meshtastic_EmergencyConfig_lora_freq_override_tag 6
#define meshtastic_EmergencyConfig_device_role_tag 7
#define meshtastic_EmergencyConfig_position_broadcast_secs_tag 8

/* Struct field encoding specification for nanopb */
#define meshtastic_EmergencyConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     emergency_mode_active,   1) \
X(a, CALLBACK, REPEATED, STRING,   whitelist_node_ids,   2) \
X(a, CALLBACK, SINGULAR, STRING,   trigger_string,    3) \
X(a, STATIC,   SINGULAR, BOOL,     allow_public_text_messages,   4) \
X(a, STATIC,   SINGULAR, UINT32,   lora_tx_power_override,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    lora_freq_override,   6) \
X(a, STATIC,   SINGULAR, UENUM,    device_role,       7) \
X(a, STATIC,   SINGULAR, UINT32,   position_broadcast_secs,   8)
#define meshtastic_EmergencyConfig_CALLBACK pb_default_field_callback
#define meshtastic_EmergencyConfig_DEFAULT NULL

extern const pb_msgdesc_t meshtastic_EmergencyConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define meshtastic_EmergencyConfig_fields &meshtastic_EmergencyConfig_msg

/* Maximum encoded size of messages (where known) */
/* meshtastic_EmergencyConfig_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
